# Generated by Django 6.0 on 2026-01-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_subscriptionplan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="billing_cycle",
            field=models.CharField(
                choices=[
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                    ("annual", "Annual"),
                    ("forever", "Forever"),
                ],
                default="monthly",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="duration_days",
            field=models.IntegerField(default=30),
        ),
    ]
