# Generated by Django 6.0 on 2026-01-11 17:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('trending_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-trending_score', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserGenerationStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books_generated_this_month', models.PositiveIntegerField(default=0)),
                ('total_books_generated', models.PositiveIntegerField(default=0)),
                ('last_generation_at', models.DateTimeField(blank=True, null=True)),
                ('month_start', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generation_stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookGenerationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mongodb_book_id', models.CharField(blank=True, max_length=24)),
                ('title', models.CharField(max_length=500)),
                ('custom_prompt', models.TextField(blank=True)),
                ('target_word_count', models.PositiveIntegerField(default=50000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('llm_request_id', models.CharField(blank=True, max_length=100)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='books/pdfs/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='books/covers/')),
                ('is_previewed', models.BooleanField(default=False)),
                ('is_downloaded', models.BooleanField(default=False)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('auto_delete_after', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.domain')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='books_bookg_user_id_020dbf_idx'), models.Index(fields=['status'], name='books_bookg_status_cc6fc2_idx'), models.Index(fields=['auto_delete_after'], name='books_bookg_auto_de_8e9567_idx')],
            },
        ),
    ]
