# Generated by Django 6.0 on 2026-01-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookgenerationrequest',
            name='cover_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='bookgenerationrequest',
            name='pdf_url',
            field=models.URLField(blank=True),
        ),
    ]
