# Generated by Django 6.0.1 on 2026-01-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_bookgenerationrequest_cover_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookgenerationrequest',
            name='cover_option',
            field=models.CharField(choices=[('auto', 'AI Generated'), ('template', 'Template Based')], default='auto', max_length=20),
        ),
    ]
