# Generated by Django 6.0.1 on 2026-01-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_bookgenerationrequest_cover_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookgenerationrequest',
            name='domain',
        ),
        migrations.AddField(
            model_name='bookgenerationrequest',
            name='domain_id',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AddField(
            model_name='bookgenerationrequest',
            name='domain_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
